# -*- coding: utf-8 -*-
"""
Generate 301 redirect rules from the rename operations committed in HEAD.

Sources of truth:
  git diff --diff-filter=R --name-status -M HEAD~1 HEAD

Outputs (all under redirects/):
  _redirects              Cloudflare Pages / Netlify format (drop at site root to activate)
  cloudflare-worker.js    Cloudflare Worker emitting real 301s (for Workers/Snippets)
  nginx-redirects.conf    Nginx rewrite rules
  .htaccess               Apache rewrite rules
  redirect-map.md         Human-readable old -> new mapping table
"""
import os
import re
import subprocess
import urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "redirects")
SITE = "https://blog.aibochinese.com"

os.makedirs(OUT, exist_ok=True)


def git_z(*args):
    """Run git with NUL-separated output so paths with spaces/newlines survive."""
    r = subprocess.run(
        ["git", "-c", "core.quotepath=false"] + list(args),
        cwd=ROOT, capture_output=True,
    )
    return r.stdout.decode("utf-8", errors="replace").split("\0")


def parse_renames():
    """Return list of (old_path, new_path) using -z name-status records."""
    toks = git_z("diff", "--diff-filter=R", "--name-status", "-M", "-z", "HEAD~1", "HEAD")
    pairs = []
    i = 0
    while i < len(toks):
        t = toks[i]
        if not t:
            i += 1
            continue
        status = t[0]
        # name-status -z: status token, then 2 paths for R/C, 1 for others
        if status in ("R", "C"):
            if i + 2 < len(toks):
                pairs.append((toks[i + 1], toks[i + 2]))
            i += 3
        else:
            i += 2
    return pairs


def name_only(filter_char):
    toks = git_z("diff", "--diff-filter=" + filter_char, "--name-only", "-z", "HEAD~1", "HEAD")
    return [t for t in toks if t.strip()]


def variants(path):
    """Yield URL path variants for a filesystem path: raw spaces and %20 encoded."""
    p = "/" + path.replace("\\", "/").lstrip("/")
    seen = []
    for v in (p, urllib.parse.quote(p, safe="/%")):
        if v not in seen:
            seen.append(v)
    return seen


def main():
    pairs = parse_renames()
    if not pairs:
        print("!!! no renames found in HEAD")
        return

    # Build rules
    rules = []  # (old_url, new_url)
    for old, new in pairs:
        for o in variants(old):
            rules.append((o, "/" + new.replace("\\", "/")))

    # Directory-level catch-all: any path that still starts with an old dir prefix
    old_dirs = sorted({os.path.dirname(o) for o, n in pairs if os.path.dirname(o)})
    new_dirs = {}
    for o, n in pairs:
        od, nd = os.path.dirname(o), os.path.dirname(n)
        if od:
            new_dirs[od] = nd

    splash = []
    for od, nd in sorted(new_dirs.items()):
        if od == nd:
            continue
        for o in variants(od):
            splash.append((o + "/*", "/" + nd + "/:splat"))

    all_rules = rules + splash
    # dedupe
    uniq = []
    seen = set()
    for a, b in all_rules:
        if a not in seen:
            seen.add(a)
            uniq.append((a, b))

    # ---------- _redirects (Cloudflare Pages) ----------
    # Cloudflare Pages separates fields by whitespace: paths MUST be percent-encoded,
    # otherwise a literal space splits the rule. Emit encoded form only.
    with open(os.path.join(OUT, "_redirects"), "w", encoding="utf-8", newline="\n") as f:
        f.write("# 301 redirects for renamed files/directories\n")
        f.write("# Generated by redirects/build_redirects.py -- do not edit by hand.\n")
        f.write("# To activate on Cloudflare Pages, copy this file to the SITE ROOT.\n")
        f.write("# Format: <from> <to> <status>  (fields are whitespace-separated)\n\n")
        seen_lines = set()
        for a, b in uniq:
            line = "%s %s 301\n" % (
                urllib.parse.quote(a, safe="/%"),
                urllib.parse.quote(b, safe="/%"),
            )
            if line not in seen_lines:
                seen_lines.add(line)
                f.write(line)

    # ---------- Cloudflare Worker ----------
    entries = []
    for a, b in uniq:
        entries.append("  %s: %s," % (repr(a).replace("'", '"'), repr(b).replace("'", '"')))
    worker = """// Cloudflare Worker: 301 redirects for renamed URLs
// Generated by redirects/build_redirects.py -- do not edit by hand.
//
// Deploy as a Worker route on blog.aibochinese.com/* (or paste into a
// Cloudflare Snippet / Ruleset "Rewrite URL" step). Exact matches are
// redirected with a real 301; splat entries (/*) map whole directories.

const REDIRECTS = {
%s
};

const EXACT = new Map();
const PREFIX = [];

for (const [from, to] of Object.entries(REDIRECTS)) {
  if (from.endsWith('/*')) {
    PREFIX.push([from.slice(0, -2), to.replace(/:splat$/, '')]);
  } else {
    EXACT.set(from, to);
  }
}
PREFIX.sort((a, b) => b[0].length - a[0].length);

export default {
  async fetch(request) {
    const url = new URL(request.url);
    let target = EXACT.get(url.pathname);

    if (target === undefined) {
      // try percent-decoded form (handles "%%20" vs literal space)
      const decoded = decodeURIComponent(url.pathname);
      target = EXACT.get(decoded);
    }

    if (target === undefined) {
      for (const [base, dest] of PREFIX) {
        if (url.pathname.startsWith(base)) {
          target = dest + url.pathname.slice(base.length);
          break;
        }
      }
    }

    if (target !== undefined) {
      return Response.redirect(new URL(target, url.origin).href, 301);
    }

    return fetch(request);
  },
};
""" % ("\n".join(entries))
    with open(os.path.join(OUT, "cloudflare-worker.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write(worker)

    # ---------- Nginx ----------
    # $uri is already percent-decoded by nginx, so match the literal (spacing) form.
    with open(os.path.join(OUT, "nginx-redirects.conf"), "w", encoding="utf-8", newline="\n") as f:
        f.write("# Nginx 301 redirects for renamed URLs\n")
        f.write("# Include inside your server {} block.\n")
        f.write("# Generated by redirects/build_redirects.py -- do not edit by hand.\n\n")
        for a, b in uniq:
            if a.endswith("/*") or "%20" in a:
                continue
            f.write("location = \"%s\" { return 301 \"%s\"; }\n" % (a.replace('"', '\\"'), b))
        for a, b in uniq:
            if not a.endswith("/*") or "%20" in a:
                continue
            base = a[:-2]
            dest = re.sub(r":splat$", "", b)
            f.write('rewrite ^"%s(.*)$" "%s$1" permanent;\n' % (base, dest))

    # ---------- Apache ----------
    # RewriteRule matches the decoded path (no leading slash); escape spaces as "\ ".
    with open(os.path.join(OUT, "htaccess-redirects.conf"), "w", encoding="utf-8", newline="\n") as f:
        f.write("# Apache 301 redirects for renamed URLs\n")
        f.write("# Copy these lines into your .htaccess (keep the RewriteEngine line once).\n")
        f.write("# Generated by redirects/build_redirects.py -- do not edit by hand.\n\n")
        f.write("RewriteEngine On\n\n")
        for a, b in uniq:
            if a.endswith("/*") or "%20" in a:
                continue
            pat = a.lstrip("/").replace(" ", "\\ ")
            f.write('RewriteRule "^%s$" "%s" [R=301,L,NE]\n' % (pat, b))
        for a, b in uniq:
            if not a.endswith("/*") or "%20" in a:
                continue
            base = a[:-2].lstrip("/").replace(" ", "\\ ")
            dest = re.sub(r":splat$", "", b)
            f.write('RewriteRule "^%s(.*)$" "%s$1" [R=301,L,NE]\n' % (base, dest))

    # ---------- Markdown map ----------
    with open(os.path.join(OUT, "redirect-map.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("# 旧 URL → 新 URL 对照表\n\n")
        f.write("本次规范化重命名共 **%d** 个文件/目录。下表为旧路径到新路径的 301 对照。\n\n" % len(pairs))
        f.write("| # | 旧路径 | 新路径 |\n|---|---|---|\n")
        for i, (o, n) in enumerate(sorted(pairs), 1):
            f.write("| %d | `%s` | `%s` |\n" % (i, o, n))
        f.write("\n## 目录级重定向\n\n")
        if new_dirs:
            f.write("| 旧目录 | 新目录 |\n|---|---|\n")
            for od, nd in sorted(new_dirs.items()):
                if od == nd:
                    continue
                f.write("| `%s/` | `%s/` |\n" % (od, nd))
        else:
            f.write("（无目录级变更）\n")
        f.write("\n## 使用方式\n\n")
        f.write("1. **Cloudflare Pages**：把 `_redirects` 复制到站点根目录，重新部署即可。\n")
        f.write("2. **Cloudflare Workers**：部署 `cloudflare-worker.js`，路由设为 `blog.aibochinese.com/*`。\n")
        f.write("3. **Nginx / Apache**：参考 `nginx-redirects.conf` 或 `htaccess-redirects.conf`。\n")
        f.write("\n> 规则同时提供了空格原样与 `%%20` 编码两种形式，避免不同客户端编码差异导致漏匹配。\n")

    print("renames      : %d" % len(pairs))
    print("rules written: %d  (exact + splat)" % len(uniq))
    print("dirs mapped  : %d" % len([1 for o, n in new_dirs.items() if o != n]))
    print("output dir   : %s" % OUT)


if __name__ == "__main__":
    main()
