// Cloudflare Worker: 301 redirects for renamed URLs
// Generated by redirects/build_redirects.py -- do not edit by hand.
//
// Deploy as a Worker route on blog.aibochinese.com/* (or paste into a
// Cloudflare Snippet / Ruleset "Rewrite URL" step). Exact matches are
// redirected with a real 301; splat entries (/*) map whole directories.

const REDIRECTS = {
  "/Rescous/free rs.html": "/Rescous/free_rs.html",
  "/Rescous/free%20rs.html": "/Rescous/free_rs.html",
  "/SMC/sm maketing.html": "/SMC/sm_maketing.html",
  "/SMC/sm%20maketing.html": "/SMC/sm_maketing.html",
  "/buildsites/chat support.html": "/buildsites/chat_support.html",
  "/buildsites/chat%20support.html": "/buildsites/chat_support.html",
  "/buildsites/cloudflare Pages.html": "/buildsites/cloudflare_pages.html",
  "/buildsites/cloudflare%20Pages.html": "/buildsites/cloudflare_pages.html",
  "/buildsites/cloudflare R2.html": "/buildsites/cloudflare_r2.html",
  "/buildsites/cloudflare%20R2.html": "/buildsites/cloudflare_r2.html",
  "/buildsites/code template.html": "/buildsites/code_template.html",
  "/buildsites/code%20template.html": "/buildsites/code_template.html",
  "/buildsites/free ocs.html": "/buildsites/free_ocs.html",
  "/buildsites/free%20ocs.html": "/buildsites/free_ocs.html",
  "/buildsites/host ssh.html": "/buildsites/host_ssh.html",
  "/buildsites/host%20ssh.html": "/buildsites/host_ssh.html",
  "/conmon funcation code/ads.html": "/conmon_funcation_code/ads.html",
  "/conmon%20funcation%20code/ads.html": "/conmon_funcation_code/ads.html",
  "/conmon funcation code/embed chat": "/conmon_funcation_code/embed_chat",
  "/conmon%20funcation%20code/embed%20chat": "/conmon_funcation_code/embed_chat",
  "/conmon funcation code/embed code template.html": "/conmon_funcation_code/embed_code_template.html",
  "/conmon%20funcation%20code/embed%20code%20template.html": "/conmon_funcation_code/embed_code_template.html",
  "/conmon funcation code/floatwechat-search.html": "/conmon_funcation_code/floatwechat-search.html",
  "/conmon%20funcation%20code/floatwechat-search.html": "/conmon_funcation_code/floatwechat-search.html",
  "/conmon funcation code/移动端底部按钮.html": "/conmon_funcation_code/mobile_bottom_bar.html",
  "/conmon%20funcation%20code/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%BA%95%E9%83%A8%E6%8C%89%E9%92%AE.html": "/conmon_funcation_code/mobile_bottom_bar.html",
  "/conmon funcation code/Page template.html": "/conmon_funcation_code/page_template.html",
  "/conmon%20funcation%20code/Page%20template.html": "/conmon_funcation_code/page_template.html",
  "/conmon funcation code/remit.html": "/conmon_funcation_code/remit.html",
  "/conmon%20funcation%20code/remit.html": "/conmon_funcation_code/remit.html",
  "/conmon funcation code/standard_nav.html": "/conmon_funcation_code/standard_nav.html",
  "/conmon%20funcation%20code/standard_nav.html": "/conmon_funcation_code/standard_nav.html",
  "/conmon funcation code/video code template.html": "/conmon_funcation_code/video_code_template.html",
  "/conmon%20funcation%20code/video%20code%20template.html": "/conmon_funcation_code/video_code_template.html",
  "/conmon funcation code/video list play.html": "/conmon_funcation_code/video_list_play.html",
  "/conmon%20funcation%20code/video%20list%20play.html": "/conmon_funcation_code/video_list_play.html",
  "/conmon funcation code/video list play bili.html": "/conmon_funcation_code/video_list_play_bili.html",
  "/conmon%20funcation%20code/video%20list%20play%20bili.html": "/conmon_funcation_code/video_list_play_bili.html",
  "/earn online.html": "/earn_online.html",
  "/earn%20online.html": "/earn_online.html",
  "/education/tutor guide.html": "/education/tutor_guide.html",
  "/education/tutor%20guide.html": "/education/tutor_guide.html",
  "/mooc/Chinese-Tokens/课程内容索引.md": "/mooc/Chinese-Tokens/course_content_index.md",
  "/mooc/Chinese-Tokens/%E8%AF%BE%E7%A8%8B%E5%86%85%E5%AE%B9%E7%B4%A2%E5%BC%95.md": "/mooc/Chinese-Tokens/course_content_index.md",
  "/mooc/Chinese-Tokens/课程总结.md": "/mooc/Chinese-Tokens/course_summary.md",
  "/mooc/Chinese-Tokens/%E8%AF%BE%E7%A8%8B%E6%80%BB%E7%BB%93.md": "/mooc/Chinese-Tokens/course_summary.md",
  "/payment/apply V-cards.html": "/payment/apply_v-cards.html",
  "/payment/apply%20V-cards.html": "/payment/apply_v-cards.html",
  "/payment/Proxy Recharge.html": "/payment/proxy_recharge.html",
  "/payment/Proxy%20Recharge.html": "/payment/proxy_recharge.html",
  "/payment/self recharge.html": "/payment/self_recharge.html",
  "/payment/self%20recharge.html": "/payment/self_recharge.html",
  "/post/apply V-cards.html": "/post/apply_v-cards.html",
  "/post/apply%20V-cards.html": "/post/apply_v-cards.html",
  "/post/chat support.html": "/post/chat_support.html",
  "/post/chat%20support.html": "/post/chat_support.html",
  "/post/China AdSense W-8BEN Tax Guide (2025).html": "/post/china_adsense_w-8ben_tax_guide_2025.html",
  "/post/China%20AdSense%20W-8BEN%20Tax%20Guide%20%282025%29.html": "/post/china_adsense_w-8ben_tax_guide_2025.html",
  "/post/cloudflare Pages.html": "/post/cloudflare_pages.html",
  "/post/cloudflare%20Pages.html": "/post/cloudflare_pages.html",
  "/post/cloudflare R2.html": "/post/cloudflare_r2.html",
  "/post/cloudflare%20R2.html": "/post/cloudflare_r2.html",
  "/post/code template.html": "/post/code_template.html",
  "/post/code%20template.html": "/post/code_template.html",
  "/post/earn online.html": "/post/earn_online.html",
  "/post/earn%20online.html": "/post/earn_online.html",
  "/post/free ocs.html": "/post/free_ocs.html",
  "/post/free%20ocs.html": "/post/free_ocs.html",
  "/post/free rs.html": "/post/free_rs.html",
  "/post/free%20rs.html": "/post/free_rs.html",
  "/post/global-payments-guide copy.html": "/post/global-payments-guide_copy.html",
  "/post/global-payments-guide%20copy.html": "/post/global-payments-guide_copy.html",
  "/post/host ssh.html": "/post/host_ssh.html",
  "/post/host%20ssh.html": "/post/host_ssh.html",
  "/post/Proxy Recharge.html": "/post/proxy_recharge.html",
  "/post/Proxy%20Recharge.html": "/post/proxy_recharge.html",
  "/post/search frame.html": "/post/search_frame.html",
  "/post/search%20frame.html": "/post/search_frame.html",
  "/post/self recharge.html": "/post/self_recharge.html",
  "/post/self%20recharge.html": "/post/self_recharge.html",
  "/post/sm maketing.html": "/post/sm_maketing.html",
  "/post/sm%20maketing.html": "/post/sm_maketing.html",
  "/post/tutor guide.html": "/post/tutor_guide.html",
  "/post/tutor%20guide.html": "/post/tutor_guide.html",
  "/conmon funcation code/*": "/conmon_funcation_code/:splat",
  "/conmon%20funcation%20code/*": "/conmon_funcation_code/:splat",
};

const EXACT = new Map();
const PREFIX = [];

for (const [from, to] of Object.entries(REDIRECTS)) {
  if (from.endsWith('/*')) {
    PREFIX.push([from.slice(0, -2), to.replace(/:splat$/, '')]);
  } else {
    EXACT.set(from, to);
  }
}
PREFIX.sort((a, b) => b[0].length - a[0].length);

export default {
  async fetch(request) {
    const url = new URL(request.url);
    let target = EXACT.get(url.pathname);

    if (target === undefined) {
      // try percent-decoded form (handles "%20" vs literal space)
      const decoded = decodeURIComponent(url.pathname);
      target = EXACT.get(decoded);
    }

    if (target === undefined) {
      for (const [base, dest] of PREFIX) {
        if (url.pathname.startsWith(base)) {
          target = dest + url.pathname.slice(base.length);
          break;
        }
      }
    }

    if (target !== undefined) {
      return Response.redirect(new URL(target, url.origin).href, 301);
    }

    return fetch(request);
  },
};
